filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - ./log/minitwit.log
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: yD2VYpavnxMz_Et3H67X

setup.kibana:
  host: "http://kibana:5601"