networks:
  main:
    name: itu-minitwit-network

services:
  app:
    # image: minitwitimage
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: minitwit_local
    networks:
      - main
    depends_on:
      - itusqlimage
    ports:
      - "5000:5000"
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=itusqlimage
      - POSTGRES_PORT=5432
    command: >
      bash -c "sleep 10 && bundle exec rake db:create db:migrate && bundle exec ruby minitwit.rb -o 0.0.0.0"
      
  itusqlimage:
    # image: postgresqlimage
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    container_name: minitwit_postgresql
    networks:
      - main
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresql_data:/var/lib/postgresql/data  # Persistent Postgres database

volumes:
  postgresql_data: