networks:
  main:
services:
  app:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    networks:
      - main
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST_REMOTE}
      - POSTGRES_PORT=5432
    command: >
      bash -c "sleep 10 && bundle exec rake db:create db:migrate && bundle exec ruby minitwit.rb -o 0.0.0.0"
