networks:
  main:
    name: itu-minitwit-network

services:
  app:
    # image: minitwitimage
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: minitwit_local_test
    networks:
      - main
    depends_on:
      - itusqlimage
    ports:
      - "5000:5000"
    environment:
      - RAILS_ENV=test
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST_TEST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    command: >
      bash -c "sleep 10 && bundle exec rake db:create db:migrate && cd Test && ls && ./run_tests.sh"
    volumes:
      - ./coverage:/app/coverage  # Mounts local `./coverage` to `/app/coverage` inside the container

  itusqlimage:
    # image: postgresqlimage
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    container_name: minitwit_postgresql_test
    networks:
      - main
    ports:
      - '5432:5432' # Default port for PostgreSQL
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/lib/postgresql/data  # Empty mount point makes this ephemeral
