# Use an official Ruby runtime as the base image
FROM ruby:3.1

# Set the working directory inside the container
WORKDIR /app

# Copy application files
COPY . .

# Install dependencies
RUN gem install bundler && bundle install

# Install test dependencies
RUN gem install rspec

# Install Python and dependencies
RUN apt-get update && apt-get install -y python3 python3-pip
# RUN pip3 install requests --break-system-packages
RUN pip3 install requests pytest --break-system-packages

# Modify the Python test file to use the correct database path so that it works for new working directory
RUN sed -i 's|DATABASE = "../minitwit.db"|DATABASE = "/app/data/minitwit.db"|' Test/minitwit_sim_api_test.py
RUN sed -i 's|with open("../schema.sql")|with open("/app/schema.sql")|' Test/minitwit_sim_api_test.py

# Run the tests
COPY Test/run_tests.sh /run_tests.sh
RUN chmod +x /run_tests.sh

# Run script
CMD ["/run_tests.sh"]
