networks:
  main:

services:
  app:
    image: niko391a/minitwitimage # specify the full image name including the username
    container_name: minitwit
    networks:
      - main
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/data  # Persistent SQLite database file

  itusqlimage:
    image: ${DOCKER_USERNAME}/postgresqlimage
    container_name: minitwit_mysql
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=root
