networks:
  main:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: minitwit_local
    networks:
      - main
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/data  # Persistent SQLite database file

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - main
    ports:
      - "9090:9090"
    depends_on:
      - app

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8080:8080"
    networks:
      - main

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    networks:
      - main
    volumes:
      - grafana_data:/var/lib/grafana  # Persist dashboards & settings
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

volumes:
  sqlite_data:
  grafana_data: