# Use an official Ruby runtime as the base image
FROM ruby:3.1

# Set the working directory inside the container
WORKDIR /app

# Copy application files
COPY . .

# Install dependencies
RUN gem install bundler && bundle install

# Install test dependencies
RUN gem install rspec

# Install Python and dependencies
RUN apt-get update && apt-get install -y python3 python3-pip
# RUN pip3 install requests --break-system-packages
RUN pip3 install requests pytest --break-system-packages

RUN pip3 install psycopg2-binary --break-system-packages

RUN pip3 install python-dotenv --break-system-packages

# Install dos2unix
RUN apt-get update && apt-get install -y dos2unix

RUN echo "Testing stage"
# Run the tests
# COPY Test/run_tests.sh /run_tests.sh
RUN dos2unix /app/Test/run_tests.sh

RUN chmod +x /app/Test/run_tests.sh

# Run script
# CMD ["/run_tests.sh"]
