networks:
  main:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: minitwit_local
    networks:
      - main
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/data  # Persistent SQLite database file

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - main
    ports:
      - "9090:9090"
    depends_on:
      - app

volumes:
  sqlite_data: