filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - ./log/minitwit.log
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTIC_PASSWORD}

setup.kibana:
  host: "http://kibana:5601"