apiVersion: 1

# This automatically add Prometheus as a data source in Grafana
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false