version: '3.3'

networks:
  main:

services:

  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    networks:
      - main
    depends_on:
      - Databaseimage
    ports:
      - '5000:5000'

  Databaseimage:
    image: ${DOCKER_USERNAME}/mydb
    container_name: minitwit_db
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root