default:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>


development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: my_app_production

# By default Active Record uses database features like prepared statements and advisory locks. 
# You might need to disable those features if you're using an external connection pooler like PgBouncer:
# LINK: https://guides.rubyonrails.org/configuring.html#configuring-a-postgresql-database
# production:
#   adapter: postgresql
#   prepared_statements: false
#   advisory_locks: false
