{
 "title": "Database dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Database query durations", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Get all messages",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(db_get_msgs_duration_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get messages by user",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(db_get_msgs_by_user_duration_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get followers by user",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(db_get_followers_by_user_duration_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}