{
 "title": "Essentials",
 "description": "Few basic metrics to test.",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Active user count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP request duration by endpoint",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests per min. by endpoint, response",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "4 * rate(http_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. of packets received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_receive_packets_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage MB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets dropped while receving",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_receive_packets_dropped_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}