server.name: kibana
server.host: "0.0.0.0"

monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

elasticsearch.hosts: [ "http://elasticsearch:9200" ]
elasticsearch.username: "kibana_system"
elasticsearch.password: "ZGDS4RgXnCdZJLxVRM1*"
