name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    manual: true

jobs:
  lint_format_and_SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install standardrb
        run: |
          gem install standardrb --user-install
          echo "$HOME/.local/share/gem/ruby/3.2.0/bin" >> $GITHUB_PATH

      - name: Run standardrb
        run: |
          standardrb

      - name: Install dawnscanner
        run: |
          gem install dawnscanner --user-install
          echo "$HOME/.local/share/gem/ruby/3.2.0/bin" >> $GITHUB_PATH
          echo "PATH=$HOME/.local/share/gem/ruby/3.2.0/bin:$PATH" >> $GITHUB_ENV
          
      - name: Clone KB repository
        run: |
          git clone https://github.com/thesp0nge/dawnscanner_knowledge_base.git $HOME/dawnscanner/kb  

      - name: Run dawnscanner
        run: |
          dawn scan .

      - name: Install rubycritic
        run: gem install rubycritic --user-install

      - name: Run rubycritic
        run: rubycritic --no-browser --format console

  testing:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_HOST_TEST: minitwit_postgresql_test
      POSTGRES_PORT: 5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test minitwit
        run: |
          # Build docker images
          docker build -t $DOCKER_USERNAME/minitwit-test-image -f Dockerfile.test .
          docker build -t $DOCKER_USERNAME/postgresqlimage -f Dockerfile.postgresql .
          

          # Run the tests
          docker compose -f docker-compose.test.yml up --exit-code-from app

        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
