name: Continuous Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    manual: true

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_HOST_TEST: minitwit_postgresql_test
      POSTGRES_PORT: 5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test minitwit
        run: |
          # Build the test image
          docker build -t $DOCKER_USERNAME/minitwit-test-image -f Dockerfile.test .

          # Build the PG image
          docker build -t $DOCKER_USERNAME/postgresqlimage -f Dockerfile.postgresql .

          # Run the tests
          docker compose -f docker-compose.test.yml up --exit-code-from app