name: Continuous Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    manual: true

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_HOST_TEST: minitwit_postgresql_test
      POSTGRES_PORT: 5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test minitwit
        run: |
          # Build and run the test images
          docker compose -f docker-compose.test.yml up --build --exit-code-from app