name: Continuous Testing

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    manual: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test minitwit
        run: |
          # Build the test image
          docker build -t $DOCKER_USERNAME/minitwittestimage -f Dockerfile.test .

          # Run the tests
          docker run --rm $DOCKER_USERNAME/minitwittestimage
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}