name: Build Report

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    manual: true

jobs:
  build-docs:
    name: Build Documentation PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # allow pushes
          fetch-depth: 0             # get full history

      - name: Install Pandoc & XeLaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex
          
          wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.15.0/pandoc-crossref-linux.tar.xz
          tar -xf pandoc-crossref-linux.tar.xz
          sudo mv pandoc-crossref /usr/local/bin/

      - name: Build report PDF
        run: |
           pandoc report/report.md \
            --pdf-engine=xelatex \
            --number-sections \
            --resource-path=report:report/images \
            -V geometry:margin=1.1in \
            -V classoption=floatfix \
            --toc \
            --toc-depth=2 \
            --include-in-header=<(echo '\usepackage{float}\floatplacement{figure}{H}') \
            --filter pandoc-crossref \
            --output report/build/BSc_group_b.pdf

      - name: Commit & push PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add report/build/BSc_group_b.pdf
          # only commit if the PDF actually changed
          git diff --cached --exit-code || git commit -m "chore: update BSc_group_b.pdf [skip ci]"
          git push
